name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ccache
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y ccache
          else
            brew install ccache
          fi

      # Set CCACHE_DIR using $GITHUB_ENV so later steps see the expanded HOME path
      - name: Set CCACHE_DIR
        run: echo "CCACHE_DIR=$HOME/.ccache" >> "$GITHUB_ENV"

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Install libsodium
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libsodium-dev pkg-config
          else
            brew install libsodium pkg-config
          fi

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DBITCHAT_WERROR=ON \
            -DBITCHAT_WITH_BLUEZ=OFF

      - name: Build
        run: cmake --build build -j

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

      - name: Smoke test (daemon + CLI)
        shell: bash
        run: |
          set -euo pipefail
          ./build/bin/bitchatd >daemon.log 2>&1 &
          DAEMON_PID=$!
          trap 'kill $DAEMON_PID 2>/dev/null || true' EXIT
          sleep 0.5
          ./build/bin/bitchatctl send "ci hello"
          ./build/bin/bitchatctl tail on
          ./build/bin/bitchatctl quit
          sleep 0.5
          if ps -p "$DAEMON_PID" > /dev/null 2>&1; then
            echo "daemon still running!" >&2
            exit 1
          fi


      - name: Show ccache stats
        run: ccache -s || true

  asan-ubsan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install libsodium
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev pkg-config

      - name: Configure (ASan+UBSan)
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g" \
            -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" \
            -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=address,undefined" \
            -DBITCHAT_WERROR=ON \
            -DBITCHAT_WITH_BLUEZ=OFF

      - name: Build
        run: cmake --build build -j

      - name: Run unit tests (exclude end-to-end)
        env:
          ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
          UBSAN_OPTIONS: print_stacktrace=1
        run: |
          ctest --test-dir build --output-on-failure